### ISSUE TITLE
Sorted usings has blank line in wrong place

### ISSUE THREAD

**Issue by xiler8** [everfor/UsingDirectiveFormatter#1]
When sorting using statments outside namespace then a blank line is inserted before all using statements at the top. Also no blank line is inserted between using statements and namespace declaration. 

This picture shows the current result:
![usingformatterbugcapture](https://user-images.githubusercontent.com/20427901/29033440-6650ef96-7b95-11e7-8eb8-3f4fc945c574.PNG)

**Comment by everfor** [comment]
Thanks for reporting the bug. The new version (1.4) should have this fixed.
