### ISSUE TITLE
Ability to add Exceptions/Rules

### ISSUE THREAD

**Issue by Ludomancer** [everfor/UsingDirectiveFormatter#2]
For example;

Making sure System directives are always at top irregardless of sort settings. 

In my case for example I'm looking for something like this;

using System*..... (Sort applies in between all System)
using UnityEngine*... (Sort applies in between all UnityEngine)
using UnityEditor*.... (Sort applies in between all UnityEditor)
using Other (Sort applies in between all Other )

In this case I've 3 rules;
System Priority > UnityEngine Priority > UnityEditor Priority > Everything else that is not defined.

**Comment by everfor** [comment]
This feature will be included in next version.
