### ISSUE TITLE
Feature request: Spacing between groups

### ISSUE THREAD

**Issue by ChaseGrant** [everfor/UsingDirectiveFormatter#3]
Hi,

Is there any chance you could add an option to add a blank line between defined groups?
That would make this perfect for me.

Thanks,
Grant.

**Comment by everfor** [comment]
Adding this feature in 1.5.2

**Comment by ChaseGrant** [comment]
Thank you 😀

**Comment by ChaseGrant** [comment]
Could we perhaps not insert this blank line when a group is blank?

**Comment by everfor** [comment]
A bugfix is included in 1.5.3. If there are other bugs (or the same bug persists) feel free to create new issues :D
