### ISSUE TITLE
Spacing group issue

### ISSUE THREAD

**Issue by ijaouani** [everfor/UsingDirectiveFormatter#6]
There is no space between the first two groups and I get two spaces at the end when I use Format Using Directive (I replace the namespace name with test for anonymous purpose) :

![image](https://user-images.githubusercontent.com/27200712/30846731-0d651026-a299-11e7-99f8-0ed05b9a6d7c.png)

UsingDirectiveFormatter Settings :

![image](https://user-images.githubusercontent.com/27200712/30846811-49f31e5c-a299-11e7-9573-cb51ef50e1e0.png)

It works the first time I installed the extension. But KO when restarting VS. I reproduced the bug on another PC with the same scenario. So I was thinking it was a save option error but all seems correct in the registry. Do you have ever tested it with VS 2017 ?

VS 15.3.5
Win 7

Thanks.

**Comment by everfor** [comment]
The bug fix will come in 1.5.6
