### ISSUE TITLE
Characters go missing when comments are present

### ISSUE THREAD

**Issue by ChaseGrant** [everfor/UsingDirectiveFormatter#7]
When format your usings and there is a comment present after the usings it corrupts them.
`using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
//test`
becomes
`using Syusing System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;`

**Comment by everfor** [comment]
Thanks for reporting. commit 88fce3e (ver 1.5.7) fixes this.
